#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define CAKEOS_TOTAL_INTERRUPTS 512

#define CAKEOS_HEAP_SIZE_BYTES 104857600
#define CAKEOS_HEAP_BLOCK_SIZE 4096
#define CAKEOS_HEAP_ADDRESS 0x01000000
#define CAKEOS_HEAP_TABLE_ADDRESS 0x00007E00

#define CAKEOS_SECTOR_SIZE 512

#define CAKEOS_MAX_FILESYSTEMS 12
#define CAKEOS_MAX_FILE_DESCRIPTORS 512

#define CAKEOS_MAX_PATH 108

#define CAKEOS_TOTAL_GDT_SEGMENTS 6

#define CAKEOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define CAKEOS_USER_PROGRAM_STACK_SIZE 1024 * 16;
#define CAKEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000;
#define CAKEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END CAKEOS_PROGRAM_VIRTUAL_ADDRESS_START - CAKEOS_USER_PROGRAM_STACK_SIZE;

#define USER_DATA_SEGMENT 0x23;
#define USER_CODE_SEGMENT 0x1b;

#define CAKEOS_MAX_PROGRAM_ALLOCATIONS 1024
#define CAKEOS_MAX_PROCESSES 12
#endif
